version: "3.8"
services:
  mysql-db:
    container_name: mysql-db
    image: mysql
    ports:
      - $DATABASE_PORT:3306
    volumes:
      - mysql-volume:/var/lib/mysql  
    environment:
      - MYSQL_ROOT_PASSWORD=$DATABASE_PASSWORD
      - MYSQL_DATABASE=$DATABASE_NAME
  express-js:
    depends_on:
      - mysql-db
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 3000:3000
volumes:
  mysql-volume: